halo2:
  radio: BM5602

packages:
  halo2: !include packages/halo2-common.yaml

esphome:
  includes:
    - halo2_protocol.h
    - bm5602_halo2.h

esp32:
  board: m5stack-atom
  flash_size: 4MB
  framework:
    type: esp-idf
