esphome:
  name: screenbar-halo2
  friendly_name: BenQ ScreenBar HALO 2
  min_version: 2026.9.0

external_components:
  - source:
      type: local
      path: components
    components: [halo2]

logger:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: "Halo2 recovery"
    password: !secret fallback_password
captive_portal:
api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_encryption_key
ota:
  - platform: esphome
    encryption:

halo2:
  id: screenbar
  light:
    id: master_lamp
    name: "ScreenBar"
    icon: mdi:desk-lamp
    initial_state:
      brightness: 91%
      color_temperature: 3925 K
  front_brightness:
    id: front_brightness
    name: "Front brightness"
    initial_value: 12
  back_brightness:
    id: back_brightness
    name: "Back brightness"
    icon: mdi:wall-sconce-flat-outline
    initial_value: 91
  sections:
    id: lamp_sections
    name: "Lighting mode"
  ultrasonic:
    id: ultrasonic_sensor
    name: "Ultrasonic sensor"
  auto_button:
    name: "Auto brightness"
  radio_status:
    id: radio_status
    name: "Radio status"

button:
  - platform: template
    name: "Resend current state"
    entity_category: diagnostic
    on_press:
      - lambda: id(screenbar).resend();
  - platform: restart
    name: "Restart"
